Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 5
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: user_id
    use_features: null
    feature_specs: null
    feature_config: null

Transformer_DCN_default: # This is a config template
    model: Transformer_DCN
    dataset_id: TBD
    loss: 'binary_crossentropy'
    metrics: [logloss, AUC]
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 64
    hidden_activations: relu
    dcn_cross_layers: 3
    dcn_hidden_units: [1024, 512, 256]
    mlp_hidden_units: [64, 32]
    num_heads: 1
    transformer_layers: 2
    transformer_dropout: 0.1
    dim_feedforward: 256
    net_dropout: 0
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 20242025
    monitor: {'AUC': 1}
    monitor_mode: 'max'
    first_k_cols: 16
