PPNet_default_001_94f56fd0:
    accumulation_steps: 1
    attention_dropout: 0.1
    attention_hidden_activations: Dice
    attention_hidden_units: [512, 256]
    attention_output_activation: null
    attention_use_softmax: false
    batch_norm: true
    batch_size: 4096
    dataset_id: MicroLens_1M_x1
    debug_mode: false
    early_stop_patience: 5
    embedding_dim: 512
    embedding_regularizer: 1.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    gate_emb_dim: 16
    gate_hidden_dim: 512
    gate_priors: [likes_level, views_level]
    group_id: user_id
    hidden_activations: ReLU
    hidden_units: [1024, 512, 256]
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 64
    metrics: [logloss, AUC]
    model: PPNet
    model_root: ./checkpoints/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
