Base:
  model_root: './checkpoints/'
  num_workers: 3
  verbose: 1
  early_stop_patience: 3
  pickle_feature_encoder: True
  save_best_only: True
  eval_steps: null
  debug_mode: False
  group_id: user_id
  use_features: null
  feature_specs: null
  feature_config: null

MIND_default:  # 新的配置模板
  model: MIND
  dataset_id: TBD
  loss: 'binary_crossentropy'
  metrics: [AUC, logloss]
  task: binary_classification
  optimizer: adam
  learning_rate: 1.0e-3
  embedding_regularizer: 0
  net_regularizer: 0
  batch_size: 4096
  embedding_dim: 64
  dnn_hidden_units: [1024, 512, 256]
  dnn_activations: ReLU
  net_dropout: 0
  batch_norm: True
  epochs: 100
  shuffle: True
  seed: 20242025
  monitor: "AUC"
  monitor_mode: 'max'
  max_len: 64
  accumulation_steps: 1
  
  # 下面是 MIND 特有的参数
  num_capsules: 4
  capsule_dim: 16
  routing_iters: 3
