DIN_MicroLens_1M_x1_001_6c08feb7:
    accumulation_steps: 1
    attention_dropout: 0.1
    attention_hidden_activations: Dice
    attention_hidden_units: [512, 256]
    attention_output_activation: null
    batch_norm: true
    batch_size: 128
    dataset_id: MicroLens_1M_x1
    debug_mode: false
    din_use_softmax: false
    dnn_activations: ReLU
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 3
    embedding_dim: 128
    embedding_regularizer: 1.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_id
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 64
    metrics: [AUC, logloss]
    model: DIN
    model_root: ./checkpoints/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
DIN_MicroLens_1M_x1_002_1fa8d93d:
    accumulation_steps: 1
    attention_dropout: 0.1
    attention_hidden_activations: Dice
    attention_hidden_units: [512, 256]
    attention_output_activation: null
    batch_norm: true
    batch_size: 128
    dataset_id: MicroLens_1M_x1
    debug_mode: false
    din_use_softmax: false
    dnn_activations: ReLU
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 3
    embedding_dim: 128
    embedding_regularizer: 1.0e-07
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_id
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 64
    metrics: [AUC, logloss]
    model: DIN
    model_root: ./checkpoints/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
