TransAct_MicroLens_1M_x1_001_b3082ec9:
    batch_norm: false
    batch_size: 512
    concat_max_pool: true
    dataset_id: MicroLens_1M_x1
    dcn_cross_layers: 3
    dcn_hidden_units: [1024, 512, 256]
    debug_mode: false
    dim_feedforward: 256
    early_stop_patience: 5
    embedding_dim: 64
    embedding_regularizer: 1.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    first_k_cols: 10
    group_id: user_id
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    mlp_hidden_units: [64, 32]
    model: TransAct
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    task: binary_classification
    time_window_ms: 86400000
    transformer_dropout: 0.1
    transformer_layers: 2
    use_features: null
    use_time_window_mask: false
    verbose: 1
