Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 5
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: user_id
    use_features: null
    feature_specs: null
    feature_config: null

BST_default: # This is a config template
    model: BST
    dataset_id: TBD
    loss: 'binary_crossentropy'
    metrics: [logloss, AUC]
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 64
    dnn_hidden_units: [128, 64, 32]
    dnn_activations: relu
    num_heads: 8
    stacked_transformer_layers: 3
    attention_dropout: 0
    net_dropout: 0
    layer_norm: True
    use_residual: True
    seq_pooling_type: mean
    use_position_emb: True
    use_causal_mask: False
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 20242025
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'
